### ISSUE TITLE
prevent requirejs error when module is not found / 404

### ISSUE THREAD

**Issue by TatjanaRo** [denkwerk/denkstrap-structure#15]
When implementing a module via "auto-init" class and data-module="modules/xxx" is it possible to check first if module is available?  to prevent this error?

require.js:141 Uncaught Error: Script error for: modules/xxx
http://requirejs.org/docs/errors.html#scripterror

Would be great if the loader would continue loading the following modules which are available instead of giving up.

**Comment by mariusbuescher** [comment]
It sounds like you need some kind of decent error handling when JavaScript modules are loaded so that the whole application does not crash only because there is one error. Is that correct?

**Comment by naxotic** [comment]
I can't reproduce this error.
