### ISSUE TITLE
Make it possible to get loading state from outside

### ISSUE THREAD

**Issue by mariusbuescher** [denkwerk/denkstrap-structure#26]
Unfortunatly the loader/core do not have any API to get the loading state from the outside. When the structure is embedded into another app there is no way to get information about the successful loading. This can lead to race conditions.

I would suggest to make a new property in the app-scope that shows that the initial module loading has finished. The loader has a promise property anyway.

This also makes it easier to test frontent applications built with denkstrap in Selenium. Recently there were some problems with this combination.

**Comment by naxotic** [comment]
Actually there is already a way to get the loading state but at the moment it can't be accessed from outside when the app is running in production mode. 

The numbers of pending modules for major and minor modules are available in the object `App.loader.pendingModules`. When both counters reach 0 the initial module loading has finished. Modules which are initialized under specific conditions are excluded from these counters. 

We should add a description about these properties in the API docs.
