### ISSUE TITLE
.csslintrc shorthand setting too harsh

### ISSUE THREAD

**Issue by ghost** [denkwerk/denkstrap-structure#41]
Example:
.some-element {
&nbsp;&nbsp;@include indent-inner();
&nbsp;&nbsp;padding-top: 1em;
&nbsp;&nbsp;padding-bottom: 1em;
}

CSS linter will throw an error on not using shorthand notation of padding. 
Alas, shorthand notation won't work as the indent-inner() mixin sets left and right padding, depending on viewport. 

More generally speaking, there's a good chance that one can't use shorthand notations for setting two or three values, as other values shall not be changed.

Recommendation: setting "shorthand": false in /.csslintrc

Best, 
Alex.

**Comment by mariusbuescher** [comment]
We had a little discussion about this issue and we think that we will not fix this one. The CSS-linter is deprecated in this setup anyway. We dropped it in favour of stylelint which will be integrated soon.
