### ISSUE TITLE
Ignore vendor files while linting

### ISSUE THREAD

**Issue by mariusbuescher** [denkwerk/denkstrap-structure#43]
https://github.com/denkwerk/denkstrap-structure/blob/2c18f4364ca2ba350595b586f386e4f95f816893/grunt/postcss.js#L18

The vendor files are linted as well in this stylelint configuration. Please fix this issue before merging this branch.

**Comment by mariusbuescher** [comment]
Best way to do this is to create a `.stylelintignore` file.

**Comment by TatjanaRo** [comment]
There seems to be an issue with .stylelintignore and postcss implementation.
https://github.com/stylelint/stylelint/issues/2950

A solution via ignore file could be the implementation of grunt stylelint.

We should fix this issue via postcss config.

**Comment by mariusbuescher** [comment]
Because of #44 we should drop the PostCSS plugin anyways.

**Comment by kaiwollhaupt** [comment]
Fix is on <code>feature/watch-task</code> branch.
