### ISSUE TITLE
Checkstyle report for CI-Server on stylelint

### ISSUE THREAD

**Issue by mariusbuescher** [denkwerk/denkstrap-structure#44]
Ther **must** be a checkstyle formatted xml-file as an output from the stylelint task for the CI-Server.

Easiest way to implement that is to drop PostCSS as the runner and use grunt-stylelint. Here the formatter [stylelint-checkstyle-formatter](https://www.npmjs.com/package/stylelint-checkstyle-formatter) works. The PostCSS plugin does not support the formatter option, so no custom formatter can be used.

I would also not recommend the use of [postcss-reporter](https://www.npmjs.com/package/postcss-reporter) because there is no adequate formatter for the checkstyle format. It must be implemented manually which is not so good.

Please keep in mind to fix this on the `feature/watch` branch.

**Comment by kaiwollhaupt** [comment]
Fix is on <code>feature/watch-task</code> branch.
