### ISSUE TITLE
Use stylelint plugin for PostCSS

### ISSUE THREAD

**Issue by mariusbuescher** [denkwerk/denkstrap-structure#9]
To remove the last dependency to ruby language PostCSS and [`stylelint`](https://www.npmjs.com/package/stylelint) should be used.

This perfectly fits with the suggestions made in #8.

**Comment by kaiwollhaupt** [comment]
Because of #43 and #44 we use grunt-stylelint instead of stylelint plugin for PostCSS.
Fixed in <code>feature/watch-task</code> with 22fdf7e .
